### PR TITLE
Home Page fixes

### LINKED ISSUE #64: Revert global font size change for h3, p.
Home page PR #61 changed h3 and p fonts globally. Would like to revert this and make fonts more consistent throughout the website.

### PR DESCRIPTION
**Pull request by RobbieZhuang**
Fixes #64 (revert font change)

Additional home page fixes:
- Hero
   - Offset hero image from the centre of the homepage instead of right
   - Make the welcome text + hero image size cap smaller
- Content
  - Resize calendar icon size + modify the padding
   - Show the next upcoming event instead of the first event ever
   - Make upcoming events section also display a message for when there are no more planned events.
   -    Make external links open in new tab

### CODE REVIEW

File: src/containers/Home.jsx [hunk 1]
```diff
@@ -38,36 +38,45 @@ const Hero = () => (
...
 
 const Content = props => {
-  var upcomingEvent = "";
-  var upcomingEventLink = "";
-  if (props.events[0] && props.events[0].title && props.events[0].link) {
-    upcomingEvent = props.events[0].title;
-    upcomingEventLink = props.events[0].link;
+  var upcomingEvent;
+  if (props.events[0]) {
+    upcomingEvent = props.events[0];
```
Comment (jenniferwills) [inline src/containers/Home.jsx:43]: oops yeah missed that earlier, thanks for the quick fix
